services:
  - type: web
    name: finance-tracker-api
    runtime: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
